# PROD Docker compose file for Next.js app
services:
  task-management-frontend:
    image: ghcr.io/genzitizens/frontend-task-management:latest
    pull_policy: always
    container_name: frontend-task-management
    restart: unless-stopped
    networks:
      - shared_network
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.taskmgmt-router.rule=Host(`task-management.exeltan.com`)
      - traefik.http.routers.taskmgmt-router.entrypoints=websecure
      - traefik.http.routers.taskmgmt-router.tls=true
      - traefik.http.routers.taskmgmt-router.tls.certresolver=myresolver
      - traefik.http.services.taskmgmt-service.loadbalancer.server.port=80
networks:
  shared_network:
    external: true
